# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangeRate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeRateWindow(object):
    def setupUi(self, ChangeRateWindow):
        ChangeRateWindow.setObjectName("ChangeRateWindow")
        ChangeRateWindow.resize(676, 363)
        ChangeRateWindow.setMaximumSize(QtCore.QSize(676, 363))
        self.centralwidget = QtWidgets.QWidget(ChangeRateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(220, 30, 221, 51))
        self.titleLabel.setObjectName("titleLabel")
        self.rateLabel = QtWidgets.QLabel(self.centralwidget)
        self.rateLabel.setGeometry(QtCore.QRect(80, 120, 91, 31))
        self.rateLabel.setObjectName("rateLabel")
        self.rateTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.rateTextBox.setGeometry(QtCore.QRect(190, 120, 381, 31))
        self.rateTextBox.setObjectName("rateTextBox")
        self.changeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.changeBtn.setGeometry(QtCore.QRect(260, 220, 121, 31))
        self.changeBtn.setObjectName("changeBtn")
        ChangeRateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChangeRateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName("menubar")
        ChangeRateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChangeRateWindow)
        self.statusbar.setObjectName("statusbar")
        ChangeRateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChangeRateWindow)
        QtCore.QMetaObject.connectSlotsByName(ChangeRateWindow)

    def retranslateUi(self, ChangeRateWindow):
        _translate = QtCore.QCoreApplication.translate
        ChangeRateWindow.setWindowTitle(_translate("ChangeRateWindow", "Change Rate"))
        self.titleLabel.setText(_translate("ChangeRateWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Change Rate</span></p></body></html>"))
        self.rateLabel.setText(_translate("ChangeRateWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">New Rate:</span></p></body></html>"))
        self.changeBtn.setText(_translate("ChangeRateWindow", "Change"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangeRateWindow = QtWidgets.QMainWindow()
    ui = Ui_ChangeRateWindow()
    ui.setupUi(ChangeRateWindow)
    ChangeRateWindow.show()
    sys.exit(app.exec_())
