# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteProduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteProductWindow(object):
    def setupUi(self, deleteProductWindow):
        deleteProductWindow.setObjectName("deleteProductWindow")
        deleteProductWindow.resize(741, 351)
        self.centralwidget = QtWidgets.QWidget(deleteProductWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(230, 30, 261, 71))
        self.titleLabel.setObjectName("titleLabel")
        self.partNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.partNoLabel.setGeometry(QtCore.QRect(130, 140, 81, 31))
        self.partNoLabel.setObjectName("itemNameLabel")
        self.itemNameTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.itemNameTextBox.setGeometry(QtCore.QRect(220, 140, 391, 31))
        self.itemNameTextBox.setObjectName("itemNameTextBox")
        self.deleteProductBtn = QtWidgets.QPushButton(self.centralwidget)
        self.deleteProductBtn.setGeometry(QtCore.QRect(300, 220, 121, 41))
        self.deleteProductBtn.setObjectName("deleteProductBtn")
        deleteProductWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(deleteProductWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 21))
        self.menubar.setObjectName("menubar")
        deleteProductWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(deleteProductWindow)
        self.statusbar.setObjectName("statusbar")
        deleteProductWindow.setStatusBar(self.statusbar)

        self.retranslateUi(deleteProductWindow)
        QtCore.QMetaObject.connectSlotsByName(deleteProductWindow)

    def retranslateUi(self, deleteProductWindow):
        _translate = QtCore.QCoreApplication.translate
        deleteProductWindow.setWindowTitle(_translate("deleteProductWindow", "DeleteProduct"))
        self.titleLabel.setText(_translate("deleteProductWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Delete Product</span></p></body></html>"))
        self.partNoLabel.setText(_translate("deleteProductWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Item Name:</span></p></body></html>"))
        self.deleteProductBtn.setText(_translate("deleteProductWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteProductWindow = QtWidgets.QMainWindow()
    ui = Ui_deleteProductWindow()
    ui.setupUi(deleteProductWindow)
    deleteProductWindow.show()
    sys.exit(app.exec_())
