# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MakeReceipt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MakeReceiptWindow(object):
    def setupUi(self, MakeReceiptWindow):
        MakeReceiptWindow.setObjectName("MakeReceiptWindow")
        MakeReceiptWindow.resize(744, 479)
        self.centralwidget = QtWidgets.QWidget(MakeReceiptWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(230, 20, 231, 51))
        self.titleLabel.setObjectName("titleLabel")
        self.billNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.billNoLabel.setGeometry(QtCore.QRect(150, 100, 71, 31))
        self.billNoLabel.setObjectName("billNoLabel")
        self.billNoTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.billNoTextBox.setGeometry(QtCore.QRect(220, 100, 311, 31))
        self.billNoTextBox.setObjectName("billNoTextBox")
        self.recpNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.recpNameLabel.setGeometry(QtCore.QRect(90, 170, 141, 31))
        self.recpNameLabel.setObjectName("recpNameLabel")
        self.recpNameTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.recpNameTextBox.setGeometry(QtCore.QRect(220, 170, 311, 31))
        self.recpNameTextBox.setObjectName("recpNameTextBox")
        self.biltyNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.biltyNoLabel.setGeometry(QtCore.QRect(140, 250, 91, 31))
        self.biltyNoLabel.setObjectName("biltyNoLabel")
        self.biltyNoTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.biltyNoTextBox.setGeometry(QtCore.QRect(220, 250, 311, 31))
        self.biltyNoTextBox.setObjectName("biltyNoTextBox")
        self.makeRecpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.makeRecpBtn.setGeometry(QtCore.QRect(280, 340, 161, 51))
        self.makeRecpBtn.setObjectName("makeRecpBtn")
        MakeReceiptWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MakeReceiptWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 21))
        self.menubar.setObjectName("menubar")
        MakeReceiptWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MakeReceiptWindow)
        self.statusbar.setObjectName("statusbar")
        MakeReceiptWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MakeReceiptWindow)
        QtCore.QMetaObject.connectSlotsByName(MakeReceiptWindow)

    def retranslateUi(self, MakeReceiptWindow):
        _translate = QtCore.QCoreApplication.translate
        MakeReceiptWindow.setWindowTitle(_translate("MakeReceiptWindow", "Make Receipt"))
        self.titleLabel.setText(_translate("MakeReceiptWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Make Receipt</span></p></body></html>"))
        self.billNoLabel.setText(_translate("MakeReceiptWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Bill No:</span></p></body></html>"))
        self.recpNameLabel.setText(_translate("MakeReceiptWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Recipient Name:</span></p></body></html>"))
        self.biltyNoLabel.setText(_translate("MakeReceiptWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Bilty No:</span></p></body></html>"))
        self.makeRecpBtn.setText(_translate("MakeReceiptWindow", "Make Receipt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MakeReceiptWindow = QtWidgets.QMainWindow()
    ui = Ui_MakeReceiptWindow()
    ui.setupUi(MakeReceiptWindow)
    MakeReceiptWindow.show()
    sys.exit(app.exec_())
