# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(689, 559)
        MenuWindow.setMaximumSize(QtCore.QSize(689, 559))
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 240, 321, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 50, 0, 50)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchProductBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchProductBtn.sizePolicy().hasHeightForWidth())
        self.searchProductBtn.setSizePolicy(sizePolicy)
        self.searchProductBtn.setObjectName("searchProductBtn")
        self.verticalLayout.addWidget(self.searchProductBtn)
        self.addProductBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addProductBtn.sizePolicy().hasHeightForWidth())
        self.addProductBtn.setSizePolicy(sizePolicy)
        self.addProductBtn.setObjectName("addProductBtn")
        self.verticalLayout.addWidget(self.addProductBtn)
        self.deleteProductBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteProductBtn.sizePolicy().hasHeightForWidth())
        self.deleteProductBtn.setSizePolicy(sizePolicy)
        self.deleteProductBtn.setObjectName("deleteProductBtn")
        self.verticalLayout.addWidget(self.deleteProductBtn)
        #self.Logo = QtWidgets.QLabel(self.centralwidget)
        #self.Logo.setGeometry(QtCore.QRect(30, 20, 131, 121))
        #self.Logo.setText("")
        #self.Logo.setPixmap(QtGui.QPixmap("google-logo-9808.png"))
        #self.Logo.setScaledContents(True)
        #self.Logo.setObjectName("Logo")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(110, -80, 441, 371))
        self.titleLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.titleLabel.setText("")
        self.titleLabel.setPixmap(QtGui.QPixmap("title.png"))
        self.titleLabel.setScaledContents(True)
        self.titleLabel.setObjectName("titleLabel")
        MenuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 21))
        self.menubar.setObjectName("menubar")
        MenuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuWindow)
        self.statusbar.setObjectName("statusbar")
        MenuWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "MainWindow"))
        self.searchProductBtn.setText(_translate("MenuWindow", "Search Product"))
        self.addProductBtn.setText(_translate("MenuWindow", "Add Product "))
        self.deleteProductBtn.setText(_translate("MenuWindow", "Delete Product"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuWindow = QtWidgets.QMainWindow()
    ui = Ui_MenuWindow()
    ui.setupUi(MenuWindow)
    MenuWindow.show()
    sys.exit(app.exec_())
