# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchProductWindow(object):
    def setupUi(self, SearchProductWindow):
        SearchProductWindow.setObjectName("SearchProductWindow")
        SearchProductWindow.resize(759, 565)
        SearchProductWindow.setMaximumSize(QtCore.QSize(759, 565))
        self.centralwidget = QtWidgets.QWidget(SearchProductWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(230, 0, 251, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.searchTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.searchTextBox.setGeometry(QtCore.QRect(150, 80, 341, 31))
        self.searchTextBox.setObjectName("searchTextBox")
        self.tableShowWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableShowWidget.setGeometry(QtCore.QRect(10, 150, 741, 311))
        self.tableShowWidget.setObjectName("tableShowWidget")
        self.tableShowWidget.setColumnCount(5)
        self.tableShowWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableShowWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShowWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShowWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShowWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShowWidget.setHorizontalHeaderItem(4, item)
        self.tableShowWidget.horizontalHeader().setDefaultSectionSize(150)
        self.clickSearchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clickSearchBtn.setGeometry(QtCore.QRect(500, 80, 91, 31))
        self.clickSearchBtn.setObjectName("clickSearchBtn")
        self.addAmountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addAmountBtn.setGeometry(QtCore.QRect(10, 470, 121, 31))
        self.addAmountBtn.setObjectName("addAmountBtn")
        self.subtractAmountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.subtractAmountBtn.setGeometry(QtCore.QRect(140, 470, 181, 31))
        self.subtractAmountBtn.setObjectName("subtractAmountBtn")
        self.changeRateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.changeRateBtn.setGeometry(QtCore.QRect(610, 470, 121, 31))
        self.changeRateBtn.setObjectName("changeRateBtn")
        SearchProductWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SearchProductWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 21))
        self.menubar.setObjectName("menubar")
        SearchProductWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SearchProductWindow)
        self.statusbar.setObjectName("statusbar")
        SearchProductWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SearchProductWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchProductWindow)

    def retranslateUi(self, SearchProductWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchProductWindow.setWindowTitle(_translate("SearchProductWindow", "Search Product"))
        self.titleLabel.setText(_translate("SearchProductWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Search Product</span></p></body></html>"))
        item = self.tableShowWidget.horizontalHeaderItem(0)
        item.setText(_translate("SearchProductWindow", "Item_Name"))
        item = self.tableShowWidget.horizontalHeaderItem(1)
        item.setText(_translate("SearchProductWindow", "Size"))
        item = self.tableShowWidget.horizontalHeaderItem(2)
        item.setText(_translate("SearchProductWindow", "Part_NO"))
        item = self.tableShowWidget.horizontalHeaderItem(3)
        item.setText(_translate("SearchProductWindow", "Quantity"))
        item = self.tableShowWidget.horizontalHeaderItem(4)
        item.setText(_translate("SearchProductWindow", "Rate"))
        self.clickSearchBtn.setText(_translate("SearchProductWindow", "Search"))
        self.addAmountBtn.setText(_translate("SearchProductWindow", "Add Amount"))
        self.subtractAmountBtn.setText(_translate("SearchProductWindow", "Subtract Amount"))
        self.changeRateBtn.setText(_translate("SearchProductWindow", "Edit Rate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchProductWindow = QtWidgets.QMainWindow()
    ui = Ui_SearchProductWindow()
    ui.setupUi(SearchProductWindow)
    SearchProductWindow.show()
    sys.exit(app.exec_())
