# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubtractAmount.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subtractAmountWindow(object):
    def setupUi(self, subtractAmountWindow):
        subtractAmountWindow.setObjectName("subtractAmountWindow")
        subtractAmountWindow.resize(633, 309)
        subtractAmountWindow.setMaximumSize(QtCore.QSize(633, 309))
        self.centralwidget = QtWidgets.QWidget(subtractAmountWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(200, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.enterAmountLabel = QtWidgets.QLabel(self.centralwidget)
        self.enterAmountLabel.setGeometry(QtCore.QRect(80, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enterAmountLabel.setFont(font)
        self.enterAmountLabel.setObjectName("enterAmountLabel")
        self.enteredAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.enteredAmount.setGeometry(QtCore.QRect(170, 80, 341, 31))
        self.enteredAmount.setObjectName("enteredAmount")
        self.subAndReceiptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.subAndReceiptBtn.setGeometry(QtCore.QRect(80, 150, 300, 31))
        self.subAndReceiptBtn.setObjectName("subAndReceiptBtn")
        self.subBtn = QtWidgets.QPushButton(self.centralwidget)
        self.subBtn.setGeometry(QtCore.QRect(400, 150, 111, 31))
        self.subBtn.setObjectName("subBtn")
        subtractAmountWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(subtractAmountWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        subtractAmountWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(subtractAmountWindow)
        self.statusbar.setObjectName("statusbar")
        subtractAmountWindow.setStatusBar(self.statusbar)

        self.retranslateUi(subtractAmountWindow)
        QtCore.QMetaObject.connectSlotsByName(subtractAmountWindow)

    def retranslateUi(self, subtractAmountWindow):
        _translate = QtCore.QCoreApplication.translate
        subtractAmountWindow.setWindowTitle(_translate("subtractAmountWindow", "Subtract"))
        self.titleLabel.setText(_translate("subtractAmountWindow", "Subtract From Amount"))
        self.enterAmountLabel.setText(_translate("subtractAmountWindow", "Enter Amount:"))
        self.subAndReceiptBtn.setText(_translate("subtractAmountWindow", "Subtract and Make Receipt"))
        self.subBtn.setText(_translate("subtractAmountWindow", "Subtract"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    subtractAmountWindow = QtWidgets.QMainWindow()
    ui = Ui_subtractAmountWindow()
    ui.setupUi(subtractAmountWindow)
    subtractAmountWindow.show()
    sys.exit(app.exec_())
